language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t unei95/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true unei95/udemy-docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "udemy-docker-react"
  env: "Udemydockerreact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-534499369729"
  bucket_path: "udemy-docker-react" 
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
