language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t unei95/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true unei95/udemy-docker-react npm run test 
